language: node_js
node_js:
  - "9"
dist: trusty
sudo: false
branches:
  only:
  - master
cache:
  directories:
    - node_modules
install:
  - npm install -g yarn
script:
  - yarn lint
  - yarn build --base-href /client/
  - mv dist/client/index.html dist/client/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/client
  on:
    branch: master